[package]
name = "libtest"
version = "0.1.0"
authors = ["fox0"]
edition = "2018"

[lib]
name = "tree"
crate-type = ["cdylib"]

[dependencies]
#cpython = { version = "0.5.2", features = ["extension-module"] }
pyo3 = { version = "0.13.2", features = ["extension-module"] }
